### ISSUE TITLE
Adding Point (0.0, 0.0) takes forever.

### ISSUE THREAD

**Issue by goggle** [JuliaGeometry/VoronoiDelaunay.jl#36] opened 2017-10-06 12:20 UTC
I wanted to get a simple triangulation of the domain (0,1)^2. So i did the following:
```
using VoronoiDelaunay
tess = DelaunayTessellation()
push!(tess, Point(1.0, 1.0))
push!(tess, Point(0.0, 1.0))
push!(tess, Point(1.0, 0.0))
push!(tess, Point(0.0, 0.0))
```
Adding the point (0.0, 0.0) gets me stuck in a infinite loop or something... Is this expected behavior? Or am I doing something wrong?

**Comment by robertdj** [comment] 2017-10-08 11:10
Not sure if this is stated explicitly in the README, but the minimum coordinate is 1 + `eps(Float64)`.

**Comment by skariel** [comment] 2017-10-08 15:20
yes it is, in the [current limitations](https://github.com/JuliaGeometry/VoronoiDelaunay.jl#current-limitations]) section. This is expected... and not a bug. closing for now

**Closed by skariel** 2017-10-08 15:20 UTC
